version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    directory: "/"
  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
