apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-manuell-behandling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  port: 8080
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 256Mi
  secureLogs:
    enabled: true
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
