apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-manuell-behandling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{image}}"
  port: 8080
  env:
    - name: KAFKA_RAPID_TOPIC
      value: teamdagpenger.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-manuell-behandling-v1
  replicas:
    min: 2
    max: 3
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 256Mi
  kafka:
    pool: "{{kafka.pool}}"
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
