apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-manuell-behandling
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: "{{image}}"
  port: 8080
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:+UseParallelGC -XX:ActiveProcessorCount=4
    - name: KAFKA_RAPID_TOPIC
      value: teamdagpenger.rapid.v1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: dp-manuell-behandling-v1
  envFrom:
    - secret: dp-manuell-behandling-unleash-api-token
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 12m
      memory: 360Mi
  kafka:
    pool: "{{kafka.pool}}"
  accessPolicy:
    outbound:
      external:
        - host: teamdagpenger-unleash-api.nav.cloud.nais.io
  secureLogs:
    enabled: true
  prometheus:
    enabled: true
    path: /metrics
  observability:
    logging:
      destinations:
        - id: loki
        - id: elastic
    autoInstrumentation:
      enabled: true
      runtime: java
